### ISSUE TITLE
Open links on iOS/Android

### ISSUE THREAD

**Issue by syfulin** [optimist-dev/vk_bridge#28]
How can I make a link so that it opens in VK Mini Apps created with Flutter and vk_bridge on an iOS / Android device.
Links open on desktop, but not on mobile.

Как можно сделать ссылку, чтобы она открывалась в VK Mini Apps созданном с помощью Flutter и vk_bridge на iOS/Android устройстве. На десктопе ссылки открываются, а на мобильных устройствах нет.

Этот код внутри VK MiniApps работает только при запуске на десктопе:
```
import 'dart:html' as html;
// ...
 GestureDetector(
    onTap: () {
      html.window.open("https://google.com", '_blank');
    },
    child: Container(
        child: Text('Open Google'),
    ),
  );
// ...
```

**Comment by otopba** [comment]
> How can I make a link so that it opens in VK Mini Apps created with Flutter and vk_bridge on an iOS / Android device.
> Links open on desktop, but not on mobile.
> 
> Как можно сделать ссылку, чтобы она открывалась в VK Mini Apps созданном с помощью Flutter и vk_bridge на iOS/Android устройстве. На десктопе ссылки открываются, а на мобильных устройствах нет.
> 
> Этот код внутри VK MiniApps работает только при запуске на десктопе:
> 
> ```
> import 'dart:html' as html;
> // ...
>  GestureDetector(
>     onTap: () {
>       html.window.open("https://google.com", '_blank');
>     },
>     child: Container(
>         child: Text('Open Google'),
>     ),
>   );
> // ...
> ```

Открывать ссылки стоит через пакет https://pub.dev/packages/url_launcher

Есть 2 но:
1) На iOS есть проблема https://github.com/flutter/flutter/issues/70858. Сейчас ссылки не открываются
2) VK не разрешает внутри платформы мини аппов уходить на сторонние сайты, скорее всего вас отклонят на ревью

**Comment by syfulin** [comment]
Мне ответила техподдержка вк. Думаю, кому-ниубдь ещё пригодится)
1. Нужно в index.html определить такую функцию:
```
<script>
function openLink(url) {
	const link = document.createElement('a')
	link.href = url
	link.setAttribute('target', '_blank')
	link.click()
}
</script>
```
(https://gist.github.com/mrqiz/a9ca8eda4b686d3c46f8356446816fb7)
2. И затем вызвать эту функцию из dart-кода, передав в неё URL:
```
js.context.callMethod('openLink', [
    'https://google.com'
]);
```

**Comment by ArthurNaida** [comment]
боже, спасибо тебе)))
