### ISSUE TITLE
Ошибка при вызове getUserInfo()

### ISSUE THREAD

**Issue by syfulin** [optimist-dev/vk_bridge#29]
При вызове метода getUserInfo() нажатием на кнопку "getUserInfo" в демо-приложении возникает такая ошибка.

Похоже, что она возникает в том случае, если у пользователя в профиле не указаны некоторые данные.

![photo_2021-02-14_18-26-32](https://user-images.githubusercontent.com/20333151/107875431-6294ec00-6ef2-11eb-879f-2b1c09a5157c.jpg)

**Comment by sanekyy** [comment]
Эта ошибка воспроизводится в браузере?

**Comment by syfulin** [comment]
@sanekyy
Нет. В web-версии всё нормально.
![Screenshot_54](https://user-images.githubusercontent.com/20333151/107875801-91ac5d00-6ef4-11eb-963b-5585abc3d365.png)

**Comment by syfulin** [comment]
@sanekyy
У класса, описывающего пользовательские данные, пометил поля "страна" и "город", как nullable.
Теперь при отсутствии этих данных в профиле пользователя не возникает ошибки:
![photo_2021-02-26_18-51-28](https://user-images.githubusercontent.com/20333151/109296881-a6c5ac00-7863-11eb-9048-d4c46350cc78.jpg)

**Comment by sanekyy** [comment]
Отлично, сделаете PR?

**Comment by otopba** [comment]
Closed via https://github.com/optimist-dev/vk_bridge/pull/31
