### ISSUE TITLE
VKBridge.instance.init() call never returns a result

### ISSUE THREAD

**Issue by aednlaxer** [optimist-dev/vk_bridge#40]
I'm facing an issue with initial call of `VKBridge.instance.init()` in my project when this call never returns a result and app never goes past this call. Turns out it's also reproducible with the example app from this repo. 

Steps to reproduce:
1. Clone the repo
2. Run the sample app from `vk_bridge/example` folder:
```sh
flutter run -d web-server
```
3. Observe never ending loading progress bar.

Browser console output:
```
developer_patch.dart:75 registerExtension() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set.
_registerExtension @ developer_patch.dart:75
js_primitives.dart:30 vk_bridge.d: vk_bridge: _sendInternal(VKWebAppInit)
js_primitives.dart:30 vk_bridge.d: send(VKWebAppInit, {})
js_primitives.dart:30 vk_bridge.d: _eventHandler: {"type":"vk-connect"}
```
According to console output above, [`print('VKBridge.init: $result');`](https://github.com/optimist-dev/vk_bridge/blob/c9e86ae1756e776c29f4cf918c043bc0404e19c5/example/lib/main.dart#L23) line is never executed.

**Comment by otopba** [comment]
To start VK Bridge, you need to open your app through the VK Mini App. Create a new application, there set up a debug address to your local machine and everything will work

**Comment by aednlaxer** [comment]
Thanks, I'll give it a shot. 

Is there a way to tell if Flutter app is running as a regular web app or inside Vk? For instance, I have a Flutter app that works both web app on my own web site and I want to make it work on Vk with extra features using Vk Mini Apps API. The only idea I've got at the moment is to use different flavors for each of these web apps.

**Comment by otopba** [comment]
In my project, we thought of the following solution:
We build the application with a flag by which we can determine that this application is built for VK flutter `build web --release --dart-define=IS_VK_MINI_APPS=true`

Then in the code we can get the value as follows:


```dart
static const isVKMiniApps = bool.fromEnvironment(
        'IS_VK_MINI_APPS',
        defaultValue: false,
    );
```

**Comment by aednlaxer** [comment]
Looks like the root cause of the initial issue was not running the app inside Vk Mini Apps. Using Vk Tunnel to run the app confirms that it works as expected.
