### ISSUE TITLE
Add a targeted advertising banner

### ISSUE THREAD

**Issue by dimstr** [optimist-dev/vk_bridge#43]
For more information, see the link below. 
1. https://vk.com/@vkappsdev-monetizaciya-servisov-vk-mini-apps
2.  https://appscentrum.com/instructions/

**Comment by dimstr** [comment]
More precisely, add the VKWebAppGetAds method.
А если точнее, то добавить метод VKWebAppGetAds.

**Comment by otopba** [comment]
@dimstr Hi! 
Please send me a link to the method from the documentation that we need to implement.  [Here](https://vk.com/dev/vkbridge?f=%D0%A0%D0%B5%D0%BA%D0%BB%D0%B0%D0%BC%D0%B0)  I see only:
[VKWebAppCheckNativeAds](https://vk.com/dev/vkbridge/vkwebappchecknativeads) and [VKWebAppShowNativeAds](https://vk.com/dev/vkbridge/vkwebappshownativeads)

**Comment by dimstr** [comment]
Link: https://appscentrum.com/instructions/

**Comment by otopba** [comment]
Метод`VKWebAppGetAds`  удален из vk-bridget https://github.com/VKCOM/vk-bridge/commit/ac28bd6161db0785803fd5a16d892d832be191cb

**Comment by otopba** [comment]
Sorry, I was wrong. Indeed such methods exist, but they are not described in VK documentation for some reason. I added them to the library of the latest version
@dimstr
