### ISSUE TITLE
setViewSettings() doesn't change icon colors on iPhone

### ISSUE THREAD

**Issue by aednlaxer** [optimist-dev/vk_bridge#47]
Looks like status bar style (icons color) is not properly set on iPhone. Calling this code right after `init` does nothing. Is there something else needs to be done to make it work or maybe it should be done in a different way?
```dart
final platform = VKBridge.instance.launchParams.platform;
if (platform == 'mobile_iphone') {
    await VKBridge.instance.setViewSettings(
        statusBarStyle: 'dark',
    );
}
```

Tested on iPhone 13 Pro with iOS 15. Older iPhone with iOS 12 and Android work fine.

**Comment by otopba** [comment]
Apparently, this is a peculiarity of the VK application. The library only allows you to make a call, we do not control the further logic
